name: Tests with reporter
on:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        working-directory: ./task_3
        run: npm install
      
      - name: Install Cypress
        working-directory: ./task_3
        run: npx cypress install
      
      - name: Run Cypress tests
        working-directory: ./task_3
        run: npm run cy:run
      
      - name: Generate Allure report
        if: always()
        working-directory: ./task_3
        run: npm run allure:generate
      
      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: ./task_3/allure-results
      
      - name: Publish Allure report to GitHub Actions
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: ./task_3/allure-report
      
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.3
        if: always()
        with:
          branch: report
          folder: task_3/allure-report
